eureka:
  client:
    serviceUrl:
      defaultZone: http://202.120.40.8:30427/eureka/
  instance:
    hostname: buyer-info-service

spring:
  application:
    name: buyer-info-service

server:
  port: 30424
