eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-host:30427/eureka/
  instance:
    hostname: buyer-info-service

spring:
  application:
    name: buyer-info-service

server:
  port: 30424
