eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-host:30427/eureka/
  instance:
    hostname: layer1-app

spring:
  application:
    name: layer1-app

item-service-name: item-info-service
buyer-service-name: buyer-info-service
order-service-name: order-service
store-service-name: store-service
homepage-service-name: store-homepage-service

server:
  port: 30428
