eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30427/eureka/

spring:
  application:
    name: layer1-app

item-service-name: item-info
buyer-service-name: buyer-info
order-service-name: order-service
store-service-name: store-service
homepage-service-name: homepage-service

server:
  port: 30428