eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-host:30427/eureka/
  instance:
    hostname: store-homepage-service
spring:
  application:
    name: store-homepage-service

server:
  port: 30426
