spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OptimusPrime1997/SoftwarteInnovation.git
          search-paths: config

server:
  port: 9001


